# SPDX-FileCopyrightText: 2023 Julian-Samuel GebÃ¼hr
# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of BorgBackup systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ backup_id }}.service"
  register: backup_service_stat

- name: Uninstall BorgBackup systemd services and files
  when: backup_service_stat.stat.exists | bool
  block:
    - name: Ensure BorgBackup systemd service is stopped
      ansible.builtin.service:
        name: "{{ backup_id }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure BorgBackup systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ backup_id }}.service"
        state: absent

    - name: Ensure BorgBackup timer does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ backup_id }}.timer"
        state: absent

    - name: Ensure BorgBackup container network does not exist via community.docker.docker_network
      when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
      community.docker.docker_network:
        name: "{{ backup_container_net }}"
        state: absent

    - name: Ensure BorgBackup container network does not exist via ansible.builtin.command
      when: devture_systemd_docker_base_container_network_creation_method == 'command'
      ansible.builtin.command:
        cmd: >-
          {{ devture_systemd_docker_base_host_command_docker }} network rm
          {{ backup_container_net }}
      register: network_deletion_result
      changed_when: backup_container_net in network_deletion_result.stdout

    - name: Ensure BorgBackup path does not exist
      ansible.builtin.file:
        path: "{{ backup_base_path }}"
        state: absent
